### ISSUE TITLE
need a detailed explanation or a paper description

### ISSUE THREAD

**Issue by expolrer** [czchal/First-Stage-Reusable-Rocket-Trajectory-Optimization-#1]
I don't know which part of the rocket specifically refers to the range, altitude, velocity and mass remaining in the program interface. Do you have a detailed explanation or a paper description? This will further help me understand this program, thank you!
![8 2](https://github.com/user-attachments/assets/68a30159-67e7-434b-9efe-f1b5d5705f1d)

**Comment by czchal** [comment]
The range refers to the final downrange displacement from the start position to the landing position as measured on the ground. 
The altitude is the final landing altitude form the ground. 
Velocity is the velocity of the vessel up on impact during landing.
mass remaining is the final mass of the rocket including fuel.
